Paths:
  # Paths should be relative to the root of the backend.
  repo_file_path: "./repos.txt" # file containing list of repos to clone
  repo_dest_dir: "./data/repos" # directory where repos will be cloned
  database_dir: "./data/database" # directory for vector database storage

# Backend:
#   host: "0.0.0.0"
#   port: 8000
#   environment: "development"

LLM:
  provider: "groq"
  model_name: "qwen/qwen3-32b"
