Paths:
  # Paths should be relative to the root of the backend.
  repo_list_path: "./repos.txt"
  env_path: "./.env"
  repo_dest_dir: "./data/repos"
  database_dir: "./data/database"
  

# API:
#   host: "0.0.0.0"
#   port: 8000
#   environment: "development"

LLM:
  provider: "groq"
  model_name: "qwen/qwen3-32b"
