Paths:
  REPO_FILE: "./repos.txt" # file containing list of repos to clone
  DEST_DIR: "./data/repos" # directory where repos will be cloned
  DATABASE_DIR: "./data/database" # directory for vector database storage

# Backend:
#   host: "0.0.0.0"
#   port: 8000
#   environment: "development"

LLM:
  provider: "openai" # e.g., openai, anthropic, ollama, local
  model_name: "gpt-4o"
  requires_api_key: true